### ISSUE TITLE
Horizontal rule (Desktop / Tablet)

### ISSUE THREAD

**Issue by mmockett** [Financial-Times/n-storylines#25]
Horizontal rule on the numbered articles should start at 1 and end at 6. At the moment, it spans the entire page width.

**Comment by gvonkoss** [comment]
@mmockett 100%? I've got a few variations on that, design wise.

**Comment by mmockett** [comment]
Designs to be added.

**Comment by pixie-ofuono** [comment]
@gvonkoss 
![state_00_m](https://cloud.githubusercontent.com/assets/24566349/21221630/0ec2c4c2-c2b6-11e6-95fe-e2fd8a128415.png)
![state_00_s](https://cloud.githubusercontent.com/assets/24566349/21221631/0ec37de0-c2b6-11e6-87cd-ecd52cce0511.png)
![state_00_xl](https://cloud.githubusercontent.com/assets/24566349/21221632/0ec49d60-c2b6-11e6-89fa-4d86dc1b77da.png)

**Comment by pixie-ofuono** [comment]
@mmockett @gvonkoss @TheoLeanse Here are all the visual designs of the component, the sketch file and marketch is located in the drive. let me know if you cannot read of see it. 

![authors_00_collapase_s](https://cloud.githubusercontent.com/assets/24566349/21225076/4201fca2-c2c7-11e6-9398-362bde424bff.png)
![authors_00_expand_s](https://cloud.githubusercontent.com/assets/24566349/21225077/4202fb66-c2c7-11e6-99f5-2a67c6fc2fa7.png)
![authors_00_m](https://cloud.githubusercontent.com/assets/24566349/21225078/42055fc8-c2c7-11e6-9f67-23d087b928ee.png)
![authors_00_xl](https://cloud.githubusercontent.com/assets/24566349/21225081/420674b2-c2c7-11e6-827e-6bdc5d04de0d.png)
![companies_lex_s](https://cloud.githubusercontent.com/assets/24566349/21225079/4205c5c6-c2c7-11e6-8ba0-6c8ffc8b6902.png)
![companies_lex_xl](https://cloud.githubusercontent.com/assets/24566349/21225080/4206550e-c2c7-11e6-9745-b55c4220a504.png)
![companies_m](https://cloud.githubusercontent.com/assets/24566349/21225082/4211d8a2-c2c7-11e6-9bf0-ca7072887c01.png)
![desktop hd_hover_state_01](https://cloud.githubusercontent.com/assets/24566349/21225083/421399a8-c2c7-11e6-90a1-36226bc90f89.png)
![other_00_m](https://cloud.githubusercontent.com/assets/24566349/21225085/421913ce-c2c7-11e6-9e00-683d5ad6d1d6.png)
![other_00_s](https://cloud.githubusercontent.com/assets/24566349/21225087/421e882c-c2c7-11e6-8dac-a2a58c1da272.png)
![other_00_xl](https://cloud.githubusercontent.com/assets/24566349/21225084/4218365c-c2c7-11e6-9eea-b0d98055d94b.png)
![state_00_m](https://cloud.githubusercontent.com/assets/24566349/21225086/4219d390-c2c7-11e6-8f84-be99a74120d5.png)
![state_00_s](https://cloud.githubusercontent.com/assets/24566349/21225088/42212dd4-c2c7-11e6-9272-629d122d02b6.png)
![state_00_xl](https://cloud.githubusercontent.com/assets/24566349/21225089/42234c4a-c2c7-11e6-8aac-e05b75ef797f.png)
![state_02_m](https://cloud.githubusercontent.com/assets/24566349/21225092/422acda8-c2c7-11e6-84bf-a9a8378b611a.png)
![state_02_s](https://cloud.githubusercontent.com/assets/24566349/21225091/422a3442-c2c7-11e6-88d5-318b10113f2b.png)
![state_02_xl](https://cloud.githubusercontent.com/assets/24566349/21225090/4229f040-c2c7-11e6-9852-8a37880318de.png)
![state_brand_m](https://cloud.githubusercontent.com/assets/24566349/21225093/422fd41a-c2c7-11e6-8e0a-7c94c4672f2b.png)
![state_brand_s](https://cloud.githubusercontent.com/assets/24566349/21225094/4231cbd0-c2c7-11e6-8355-784e714fca8a.png)
![state_brand_xl](https://cloud.githubusercontent.com/assets/24566349/21225095/4233ab80-c2c7-11e6-82f7-32cb6e470e6c.png)
![topic_stream_00_m](https://cloud.githubusercontent.com/assets/24566349/21225097/423a9742-c2c7-11e6-90d0-6b3404d22632.png)
![topic_stream_00_s](https://cloud.githubusercontent.com/assets/24566349/21225096/423a71e0-c2c7-11e6-803c-bc8e40cd8712.png)
![topic_stream_00_xl](https://cloud.githubusercontent.com/assets/24566349/21225098/423be4bc-c2c7-11e6-8710-934e16a7c9ca.png)

**Comment by gvonkoss** [comment]
https://github.com/Financial-Times/n-storylines/pull/53
