### ISSUE TITLE
Scroll on Mobile

### ISSUE THREAD

**Issue by mmockett** [Financial-Times/n-storylines#27]
On Default and Small devices, the timeline should travel off the page to indicate that it can be scrolled:

<img width="506" alt="screen shot 2016-12-13 at 17 07 00" src="https://cloud.githubusercontent.com/assets/8199751/21152703/5e259ea2-c15f-11e6-9e15-cd183e745ce3.png">

**Comment by gvonkoss** [comment]
https://github.com/Financial-Times/n-storylines/pull/54
