### ISSUE TITLE
Move Years / Months button out of timeline

### ISSUE THREAD

**Issue by mmockett** [Financial-Times/n-storylines#32]
And put above Timeline

**Comment by mmockett** [comment]
Design to be attached.

**Comment by pixie-ofuono** [comment]
![state_02_m](https://cloud.githubusercontent.com/assets/24566349/21191741/0af9b9c4-c21e-11e6-83e5-0836289bc8ad.png)
![state_02_s](https://cloud.githubusercontent.com/assets/24566349/21191742/0b0a04d2-c21e-11e6-97d5-0294223368cd.png)
![state_02_xl](https://cloud.githubusercontent.com/assets/24566349/21191743/0b124836-c21e-11e6-809c-2b727e47bd95.png)
 @gvonkoss
