### ISSUE TITLE
Zoom Transitions missing

### ISSUE THREAD

**Issue by mmockett** [Financial-Times/n-storylines#33]
Consult prototype to see an example of what this should look like.

**Comment by knicolai-git** [comment]
Please takes this as a reference for the transition only: http://share.framerjs.com/s8wxa6bddzrp/

**Comment by gvonkoss** [comment]
This isn't an option at the moment, because we re–render the component for each level. 
If it's very relevant, we can revisit this further down the line (once the component has passed A/B testing perhaps? 🎉 )

**Comment by mmockett** [comment]
Shaaaame - but as long as we have a good solution for #31 it should be clear what's happening to the user.
