### ISSUE TITLE
Tracking missing from key article links

### ISSUE THREAD

**Issue by sbotchey-ft** [Financial-Times/n-storylines#37]
![screen shot 2016-12-13 at 15 40 19](https://cloud.githubusercontent.com/assets/19425853/21181905/16f07e96-c1f8-11e6-8b3e-c4872dd5cbd7.png)

**Comment by gvonkoss** [comment]
have just merged a fix for this! -> https://github.com/Financial-Times/n-storylines/pull/52 @sbotchey-ft let me know if it's up to scratch :+1:
