### ISSUE TITLE
IE10 - Default view stretched outside screen

### ISSUE THREAD

**Issue by sbotchey-ft** [Financial-Times/n-storylines#38]
I suspect flex not implemented for this browser. 
![screen shot 2016-12-14 at 13 30 10](https://cloud.githubusercontent.com/assets/19425853/21184092/c9c809b2-c202-11e6-8505-dc5cbdb2e3de.png)

**Comment by gvonkoss** [comment]
I think this is related to [this issue](https://github.com/Financial-Times/n-storylines/issues/30), so as soon as I get the PR merged to fix that,  I'll be asking you to try again!

**Comment by gvonkoss** [comment]
Closing this, as IE10 will only be serving core!
