### ISSUE TITLE
Key Article numbers missing/hidden

### ISSUE THREAD

**Issue by sbotchey-ft** [Financial-Times/n-storylines#39]
![screen shot 2016-12-14 at 13 57 10](https://cloud.githubusercontent.com/assets/19425853/21184683/7a6ee568-c205-11e6-8eb9-6d7354c63819.png)

![screen shot 2016-12-14 at 14 01 16](https://cloud.githubusercontent.com/assets/19425853/21184872/4fb757aa-c206-11e6-80e8-091ea684c3a0.png)

**Comment by mmockett** [comment]
We've decided not to address this for the time being because it's difficult!

**Comment by mmockett** [comment]
We can re-open this if we get time to look at a UX solution for it.
