### ISSUE TITLE
Vertical rule on mobile missing

### ISSUE THREAD

**Issue by mmockett** [Financial-Times/n-storylines#47]
The vertical line connecting the 6 articles seems to have disappeared:

![screen shot 2016-12-16 at 09 47 22](https://cloud.githubusercontent.com/assets/8199751/21258382/9eb27398-c374-11e6-9951-9c87cc08f02c.png)

**Comment by gvonkoss** [comment]
https://github.com/Financial-Times/n-storylines/pull/53
