### ISSUE TITLE
Hover boxes on smaller viewports visually clip

### ISSUE THREAD

**Issue by mmockett** [Financial-Times/n-storylines#62]
They show up like this on anything smaller than M:

![screen shot 2017-01-03 at 15 16 21](https://cloud.githubusercontent.com/assets/8199751/21612125/c921d7ac-d1c7-11e6-8ccb-22ab6feb962c.png)

**Comment by gvonkoss** [comment]
Isn't anything smaller than M technically a mobile screen? Because these don't show on mobile (or tablet because it's a hover)

**Comment by mmockett** [comment]
Technically you could have a desktop viewport that is this small. Is there a way to actively hide them at a certain breakpoint? Might be easier to do that than ensure they show correctly on smaller windows.

**Comment by gvonkoss** [comment]
:+1: I'll do that

**Comment by gvonkoss** [comment]
https://github.com/Financial-Times/n-storylines/pull/66
